name: Docker runner image

on:
  push:
    branches:
      - main
    paths:
      - '.devcontainer/Dockerfile'
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and push image
    runs-on: ubuntu-20.04
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    strategy:
      matrix:
        python-version: [ 2.7 ]
        is-ci: [ 'true' ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        run: |
          docker build --build-arg PYTHON_VERSION="${{ matrix.python-version }}" \
          --build-arg IS_CI="${{ matrix.is-ci }}" \
          --no-cache \
          --progress=plain \
          --tag $DOCKER_USERNAME/pydeps-agent:ci-2.7-test \
          --file docker-images/agent/Dockerfile .

      - name: Push image to Docker Hub
        run: |
          docker push $DOCKER_USERNAME/pydeps-agent:ci-2.7-test

# Built with ❤ by [Pipeline Foundation](https://pipeline.foundation)
