name: Test

on: [ push, workflow_dispatch ]

jobs:
  test:
    name: Build and push image
    runs-on: ubuntu-20.04
    steps:
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
